project:
  type: website
  output-dir: docs

website:
  title: "CCSPP APR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: all-grantees.qmd
        text: "All Grantees"
      - href: RTACs/index.qmd
        text: "RTACs"

  sidebar:
    - title: "All Grantees"
      contents: 
       - all-grantees.qmd

    - title: "RTACs"
      contents: 
       - auto: "RTACs"
    
       
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

