project:
  type: website
  output-dir: docs

website:
  title: "CCSPP APR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Capacity Building Strategies.qmd
        text: "CBS"      
      - href: Engaging Educational Partners.qmd
        text: "Engaging Partners"      
      - href: Goals and Actions.qmd
        text: "Goals & Actions"    
      - href: WCFSI.qmd
        text: "Whole-Child Family Supports"


  sidebar:
    - title: "Statewide"
      contents: 
       - statewide.qmd

    - title: "RTACs"
      contents: 
       - auto: "RTACs"
    
       
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

